### ISSUE TITLE
Create pipeline for add person to user

### ISSUE THREAD

**Issue by terjetopland** [terjetopland/ski-merke#46]
- [x] create Service and IService
- [x] Add Service to program.cs
- [x] create controller
- [x] add controller path in context in setupProxy
- [x] create a form react
- [x] create a task to add person to current user in controller
- [x] create api to use the controller and add the values from the form

**Comment by terjetopland** [comment]
@VillereV vet du hvordan jeg kan få tak i current logged in user? Har prøvd å googlet mye, men finner ikke noe metode i kontrolleren som fungerer....
Branchen er denne: [46-create-pipeline-for-add-person-to-user
terjetopland/ski-merke](https://github.com/terjetopland/ski-merke/tree/46-create-pipeline-for-add-person-to-user)

**Comment by VillereV** [comment]
Litt hjelp på veien: 
Slik det er satt opp nå, er endepunkt for å legge til person åpen for alle. Alle endepunkter for å hente ut brukerinformasjon må beskyttes.

Controlleren kan annoteres med ‘[Authorize]’.

Når det er på plass kan controlleren vite hvem innlogget bruker er. Det må også sendes med mer data fra klienten for at backend vite noe som helst om hvem som kommuniserer med api’et. Dere bruker bearer token til dette, som må sendes med i header i alle http-requestene som krever autentisering. Eksempel på hvordan det kan gjøres ligger i komponenten som henter værdata.

**Comment by terjetopland** [comment]
Takk for det.
Skal se på hvordan dette er gjort i værdata :-)
